SCORING_CONFIG = {
    "weights": {
        "value_fundamental": 0.25,
        "trend_momentum": 0.45,
        "macro": 0.05,
        "fund_flow": 0.15,
        "event_news": 0.10,
    },
    "value_fundamental": {
        "sub_weights": {
            "pe_score": 0.2,
            "pb_score": 0.2,
            "roe_score": 0.2,
            "earnings_quality_score": 0.2,
            "debt_ratio_score": 0.2,
        },
        "pe_percentile_bins": [
            (0, 10, 10),
            (10, 20, 9),
            (20, 30, 8),
            (30, 40, 7),
            (40, 50, 6),
            (50, 60, 5),
            (60, 70, 4),
            (70, 80, 3),
            (80, 85, 2),
            (85, 90, 1),
            (90, 100, 0),
        ],
        "pb_percentile_bins": [
            (0, 10, 10),
            (10, 20, 9),
            (20, 30, 8),
            (30, 40, 7),
            (40, 50, 6),
            (50, 60, 5),
            (60, 70, 4),
            (70, 80, 3),
            (80, 85, 2),
            (85, 90, 1),
            (90, 100, 0),
        ],
        "roe_bins": [
            (-float("inf"), 0, 0),
            (0, 5, 1),
            (5, 10, 3),
            (10, 15, 5),
            (15, 20, 7),
            (20, float("inf"), 9),
        ],
        "roe_bonus": {
            "consecutive_2_years_above_15": 1,
            "consecutive_3_years_above_15": 2,
        },
        "roe_penalty": {
            "yoy_drop_above_5": -2,
            "consecutive_2_years_drop": -3,
        },
        "gross_margin_bins": [
            (0, 10, 1),
            (10, 20, 3),
            (20, 30, 5),
            (30, 40, 7),
            (40, float("inf"), 9),
        ],
        "gross_margin_bonus": {
            "yoy_increase_above_5": 1,
        },
        "gross_margin_penalty": {
            "yoy_drop_above_5": -1,
            "consecutive_2_years_drop": -2,
        },
        "net_margin_bins": [
            (-float("inf"), 0, 0),
            (0, 5, 3),
            (5, 10, 5),
            (10, 15, 7),
            (15, float("inf"), 9),
        ],
        "debt_ratio_bins": [
            (-float("inf"), 40, 9),
            (40, 50, 7),
            (50, 60, 5),
            (60, 70, 3),
            (70, 80, 1),
            (80, float("inf"), 0),
        ],
        "earnings_quality_weights": {
            "roe_score": 0.4,
            "cash_flow_score": 0.3,
            "growth_stability_score": 0.3,
        },
        "cash_flow_bins": [
            "continuous_positive_and_growing",
            "continuous_positive",
            "occasional_negative_but_overall_positive",
            "continuous_negative",
        ],
        "cash_flow_scores": [9, 6, 4, 0],
        "growth_stability_bins": [
            "continuous_3_years_growth",
            "continuous_2_years_growth",
            "basically_stable",
            "continuous_decline",
        ],
        "growth_stability_scores": [9, 6, 4, 1],
    },
    "trend_momentum": {
        "sub_weights": {
            "five_day_return_score": 0.30,
            "twenty_day_return_score": 0.40,
            "sixty_day_momentum_score": 0.00,
            "fund_inflow_days_score": 0.30,
        },
        "five_day_return_bins": [
            (-float("inf"), -5, 0),
            (-5, -2, 2),
            (-2, 0, 4),
            (0, 2, 6),
            (2, 5, 8),
            (5, float("inf"), 10),
        ],
        "twenty_day_return_bins": [
            (-float("inf"), -10, 0),
            (-10, -5, 1),
            (-5, 0, 3),
            (0, 3, 5),
            (3, 6, 7),
            (6, 10, 8),
            (10, 15, 9),
            (15, float("inf"), 10),
        ],
        "sixty_day_momentum_bins": [
            (-float("inf"), -5, 0),
            (-5, 0, 2),
            (0, 5, 4),
            (5, 10, 6),
            (10, 15, 8),
            (15, float("inf"), 10),
        ],
        "fund_inflow_days_bins": [
            ("continuous_outflow", 0),
            ("1-3_days", 2),
            ("3-5_days", 4),
            ("5-7_days", 6),
            ("7-10_days", 8),
            ("10+_days", 10),
        ],
        "chase_high_threshold": 15,
    },
    "macro": {
        "bins": [
            (-float("inf"), 2, 1),
            (2, 3, 3),
            (3, 4, 5),
            (4, 5, 7),
            (5, 6, 9),
            (6, float("inf"), 10),
        ],
        "pmi_bins": [
            (-float("inf"), 40, 1),
            (40, 45, 3),
            (45, 50, 5),
            (50, 55, 7),
            (55, 60, 9),
            (60, float("inf"), 10),
        ],
        "indicator_weights": {
            "gdp_growth": 0.25,
            "pmi": 0.25,
            "m2_growth": 0.25,
            "policy_score": 0.25,
        },
    },
    "fund_flow": {
        "bins": [
            (-float("inf"), 2, 1),
            (2, 3, 3),
            (3, 4, 5),
            (4, 5, 7),
            (5, 6, 9),
            (6, float("inf"), 10),
        ],
        "indicator_weights": {
            "northbound_flow": 0.35,
            "margin_balance": 0.30,
            "main_fund_flow": 0.35,
        },
    },
    "event_news": {
        "bins": [
            (-float("inf"), 2, 1),
            (2, 3, 3),
            (3, 4, 5),
            (4, 5, 7),
            (5, 6, 9),
            (6, float("inf"), 10),
        ],
    },
    "blacklist": {
        "consecutive_loss_years": 2,
        "st_flag": True,
        "turnover_threshold": 20,
        "pe_percentile_threshold": 90,
        "chase_high_warn_threshold": 15,
    },
    "rating": {
        "excellent": 9,
        "good": 8,
        "medium": 6,
        "watch": 4,
        "reject": 0,
    },
}